### ISSUE TITLE
Invalid stickler-ci configuration option

### ISSUE THREAD

**Issue by markstory** [reactive-firewall/PiAP-Webroot#26]
I run @stickler-ci and noticed that your current configuration is resulting in your reviews failing. 

https://github.com/reactive-firewall/PiAP-Webroot/blob/43b441682ad3b6f6ec009e6f38a6f9617ff0f8c7/.stickler.yml#L4

The `exclude` option of shellcheck expects a list of shellcheck error ids. Perhaps you want to use the [files.ignore](https://stickler-ci.com/docs#config) option instead?

**Comment by reactive-firewall** [comment]
Thanks for catching this. And double thanks for the clear insight to the configuration. 

While related to Reactive-firewall/Pocket-PiAP#86
This is a separate issue. I only had wanted to have shellcheck ignore ['tests', 'webroot/PiAP/bin/*'] 
and all checks ignore ['*/*.pyc', '.tox/*', '*.pyc', '*~', '.git', '__pycache__', '*/__pycache__/*']

Triage:
- Issue Confirmed as Misconfiguration.

Related ToDo:
- task needed to read up on shellcheck (to determine if it is capable of the granularity I hope for)
- task needed for reviewing configuration notes on stickler-ci
